const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 210,
      counInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'hight quqlity shirt',
    },
    {
      name: 'Adidas  Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      counInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'hight quqlity shirt',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 100,
      counInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'hight quqlity shirt',
    },
    {
      name: 'Adidas Fit Pant',
      slug: 'adidas-Fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      counInStock: 5,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'hight quqlity shirt',
    },
  ],
};
export default data;
